language: python
python:
  - "2.7.11"
# command to install dependencies
#install:
env:
  - CONFIG="pip install pytest==3.2.1"
#	- pip install -r requirements.txt
# command to run tests
script: pytest
